--
# GlusterFS Client side
- name: create mount point for glusterfs volumes
  sudo: yes
  file:
          state: directory
          name: "{{ item.bricks[0] | basename }}"
          recurse: yes
          mode: 0755
  with_items: glusterfs_volumes
  tags:
    - glusterfs

