---
# something that applies to all app servers.
- include: server.yml
  when: "'master' in group_names"
  tags:
   - glusterfs

# something that applies to all app servers.
- include: client.yml
  when: "'node' in group_names"
  tags:
   - glusterfs
