---
# GlusterFS Server side
glusterfs_install_server: True
glusterfs_volumes:
        - name: scratch
          cluster: "{{ groups['master'] | join(',') }}" 
          host: '{{ ansible_hostname }}'
          options:
#                  auth.allow: "{{ groups['node'] | join(',') }}" 
                  auth.allow: "192.168.0.*"
                  nfs.disable: 'on'
          force: True
          bricks:
                  - /data/glusterfs/scratch/brick1/brick
