---
# GlusterFS Server side
glusterfs_install_server: True
glusterfs_volumes:
        - name: scratch
          cluster: "{% for node in groups['master'] %}{{ hostvars[node][access_ip_v4] }}{% if not loop.last %},{% endif %}{% endfor %}"
          host: '{{ ansible_fqdn }}'
          options:
                  auth.allow: "{% for node in groups['node'] %}{{ hostvars[node][access_ip_v4] }}{% if not loop.last %},{% endif %}{% endfor %}"
                  nfs.diable: 'on'
          bricks:
                  - /data/glusterfs/scratch/brick1/brick
          tags:
                  - glusterfs 

